;─────────────────────────────────────────[ konamask configuration ]─────────────────────────────────────────;

# Do not remove components/parameter names from this file, otherwise konamask will not be able to properly initialize.
# Most commets will be removed if in-app settings are applied.

# Audio / TTS parameters
speech_rate   = 150             ; words per minute      (default: 150, min: 0, max: 65535 | type: unsigned short)
speech_pitch  = 50              ;                       (default:  50, min: 0, max: 65535 | type: unsigned short)
speech_volume = 100             ; output volume         (default: 100, min: 0, max: 65535 | type: unsigned short)
speech_vociebank    = en-us     ; voicebank, that you want to use (default: en-us)

# Input / STT parameters
voskapi_model_path  = ./model   ; define path (folder location) to a vosk model (download from: https://alphacephei.com/vosk/models if website is down, use https://archive.nightvoid.com/Development/konamask/)
silence_threshold = 200         ; amplitude threshold                        (default:  200 | type: unsigned int)
silence_timeout = 1000          ; required silence duration (ms) to finalize (default: 1000 | type: unsigned int)

# User interface parameters
enable_user_interface = true    ; enables/disables UI (default: true | enable: true, disable: false | type: boolean)
enable_logging_to_file = false  ; enables/disables logging (default: false | enable: set path to, disable: false | type: boolean)

ui_custom_font = ./include/Outfit-SemiBold.ttf ; custom font family directory (default: | type: const char*)
ui_font_size = 14               ; custom font size (default: 16, min: 8, max: 72 | type: int) *required if using cusom font | max & min may differ with the font you're using, these are common values

ui_bgc_red = 45                 ; chagnes the red factor of the background color   (default: 45, min: 0, max: 255 | type: float)
ui_bgc_green = 20               ; chagnes the green factor of the background color (default: 20, min: 0, max: 255 | type: float)
ui_bgc_blue = 60                ; chagnes the blue factor of the background color  (default: 60, min: 0, max: 255 | type: float)

ui_theme_red = 220              ; chagnes the red factor of the interface theme color   (default: 167, min: 0, max: 255 | type: float)
ui_theme_green = 26             ; chagnes the green factor of the interface theme color (default:  42, min: 0, max: 255 | type: float)
ui_theme_blue = 98              ; chagnes the blue factor of the interface theme color  (default:  92, min: 0, max: 255 | type: float)

enable_custom_background = true ; enables/disables custom background image  (default: false | enable: true, disable: false | type: boolean) *if set to true, please set your custom image at "~/.config/konacode/konamask/background" (remove image extension)
enable_window_borders = true    ; enables/disables window borders           (default:  true | enable: true, disable: false | type: boolean)

# Advanced parameters (do not edit, unless you know, what you're doing)
pa_sample_spec_rate = 22050     ; pulseaudio sample rate                                    (default: 22050 | type: int)
buffer_factor       = 0.05      ; portaudio buffer (smaller buffer -> smaller latency)      (default: 0.05  | type: double)

;────────────────────────────────────────────────────────────────────────────────────────────────────────────;
